### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by nicolasmaia** [breizoreol/memanki#1]
Sorry, the instructions weren't clear for me. How do I run the program?

**Comment by matthieu-rolland** [comment]
Hello, do you have nodejs installed on your machine?

You can do what is written in the code example inside any nodejs project.

If you're not in a nodejs project and just want to do the conversion, write the code in a js file and call it with nodejs in command line. Anki files will be generated in the same folder. Or even easier, use the command line utility:

https://github.com/breizoreol/memanki-cli

**Comment by nicolasmaia** [comment]
Thanks!
